<?php

// Borrowed with great gratitude from:
// http://www.phpbuilder.com/articles/application-architecture/security/using-a-json-web-token-in-php.html


function generateJWTHS256($payload, $privateKey){

// Convert $payload to string if not already a string.
if(gettype ($payload) != 'string'){
    $payload = json_encode($payload);
}   

// base64url encodes the header json
$encoded_header = strtr(rtrim(base64_encode('{"alg": "HS256","typ": "JWT"}'), '='), '+/', '-_');

// base64url encodes the payload json
$encoded_payload = strtr(rtrim(base64_encode($payload), '='), '+/', '-_');

// base64 strings are concatenated to one that looks like this
$header_payload = $encoded_header . '.' . $encoded_payload;

// Creating the signature, a hash with the s256 algorithm and the secret key. The signature is also base64url encoded.
$signature = strtr(rtrim(base64_encode(hash_hmac('sha256', $header_payload, $privateKey, true)), '='), '+/', '-_');

// Creating the JWT token by concatenating the signature with the header and payload, that looks like this:
$jwt_token = $header_payload . '.' . $signature;

//listing the resulted  JWT
return  $jwt_token;

}

function checkJWTHS256($jwt_token, $privateKey){

// Split a string by '.' 
$jwt_values = explode('.', $jwt_token);

if(count($jwt_values) !== 3) {
    return false;
}

// Extract and validate header
$encoded_header = $jwt_values[0];
$header_json = base64url_decode($encoded_header);
$header = json_decode($header_json, true);

// Validate algorithm is HS256
if(!isset($header['alg']) || $header['alg'] !== 'HS256') {
    return false;
}

// extracting the signature from the original JWT 
$recieved_signature = $jwt_values[2];

// concatenating the first two arguments of the $jwt_values array, representing the header and the payload
$recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];

// creating the Base 64url encoded new signature generated by applying the HMAC method to the concatenated header and payload values
$resultedsignature = strtr(rtrim(base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $privateKey, true)), '='), '+/', '-_');

// checking if the created signature is equal to the received signature
    if(hash_equals($resultedsignature, $recieved_signature)) {

	// If everything worked fine, if the signature is ok and the payload was not modified you should get a success message
	return base64url_decode($jwt_values[1]);
    } else {
        return false;
    }

}

// Helper function for base64url decoding
function base64url_decode($data) {
    return base64_decode(strtr($data, '-_', '+/') . str_repeat('=', 3 - (3 + strlen($data)) % 4));
}

function random_str($length){
    $res ="";
    for($cnt=0; $cnt<($length+1); $cnt++){
        
        $rnd = mt_rand(0,62);
        $res2 = $cnt;
        
        if($rnd<10){ $res .= chr($rnd+48);}
        elseif($rnd<37){$res .= chr($rnd+54);}
        else{$res .= chr($rnd+60);}
    }
    return $res;
}


